llms:
  - name: claude
    anthropic:
      token: ${ANTHROPIC_API_KEY}
    model: claude-opus-4-20250514

agents:
  - name: main
    llm: claude
    default_tools: true
    tools: []
    default_skills: true
    skills: []

channels:
  - name: websocket
    type: websocket

bindings:
  - binding_id: main@websocket
    agent: main
    channel: websocket
    require_mention: false
